services:
  # Backend API Service
  - type: web
    name: reviewer-recommendation-backend
    runtime: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        sync: false
    healthCheckPath: /health
    
  # Frontend Service
  - type: web
    name: reviewer-recommendation-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: VITE_API_BASE
        value: https://reviewer-recommendation-system.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
