[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
    "pip install --no-cache-dir --upgrade pip setuptools wheel",
    "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "uvicorn app:app --host 0.0.0.0 --port $PORT --workers 1"
